; AUTO-GENERATED by scripts/sync_queries.py
; Edit only the LOCAL section in composed files (core/queries, udl/queries, objectscript_routine/queries).
; File: indents.scm
; === BEGIN EXPR ===
; === END EXPR ===
; === BEGIN CORE ===
"{" @indent.begin

"}" @indent.end

; === END CORE ===
; === BEGIN LOCAL ===
; === END LOCAL ===
